const userRoles = {
  ICT_ADMIN: "ICT_ADMIN",
  FINANCE_ADMIN: "FINANCE_ADMIN",
  INSTRUCTORS_ADMIN: "INSTRUCTORS_ADMIN",
  PROSPECTIVE_STUDENT: "PROSPECTIVE_STUDENT",
  ALUMNI: "ALUMNI",
  STUDENT: "STUDENT",
  INSTRUCTOR: "INSTRUCTOR",
};

export default userRoles;
